### ISSUE TITLE
Please describe functionality of this program and how to run it with sdrangel

### ISSUE THREAD

**Issue by satfan52** [AI6YP/pluton#1]
Hello,

I have compiled sdrangel and I can use it fine with my putosdr.
I am trying to understand if your script or code could be of any added value for me, ie, to use the plutosdr with sdrangel
Thanks for clarifying

**Comment by drom** [comment]
This repo contains my experiments on controlling PlutoSDR and SDRangel from NodeJS. It is quite out of date and not very useful right now.
